### ISSUE TITLE
Hi

### ISSUE THREAD

**Issue by blutooth** [SamMatzko/SorteryLib#2]
Hi Sam, I noticed some of your posts on stackoverflow and wondered if you would be interested in work opportunities in Rust. If so, let's connect!

**Comment by SamMatzko** [comment]
@blutooth Thank you very much for the offer, but unfortunately I'm still a student. However, I'm glad that you think that I'm worth noting, and when I'm open for job opportunities (which sadly won't be for a while), I'll make sure to put it on my SO and GitHub profiles.
